# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RonService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10RonService.proto\x12\nRonService\"\x1e\n\x0eSendSmsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fSendSmsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2R\n\nRonService\x12\x44\n\x07SendSms\x12\x1a.RonService.SendSmsRequest\x1a\x1b.RonService.SendSmsResponse\"\x00\x62\x06proto3')



_SENDSMSREQUEST = DESCRIPTOR.message_types_by_name['SendSmsRequest']
_SENDSMSRESPONSE = DESCRIPTOR.message_types_by_name['SendSmsResponse']
SendSmsRequest = _reflection.GeneratedProtocolMessageType('SendSmsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSREQUEST,
  '__module__' : 'RonService_pb2'
  # @@protoc_insertion_point(class_scope:RonService.SendSmsRequest)
  })
_sym_db.RegisterMessage(SendSmsRequest)

SendSmsResponse = _reflection.GeneratedProtocolMessageType('SendSmsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDSMSRESPONSE,
  '__module__' : 'RonService_pb2'
  # @@protoc_insertion_point(class_scope:RonService.SendSmsResponse)
  })
_sym_db.RegisterMessage(SendSmsResponse)

_RONSERVICE = DESCRIPTOR.services_by_name['RonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDSMSREQUEST._serialized_start=32
  _SENDSMSREQUEST._serialized_end=62
  _SENDSMSRESPONSE._serialized_start=64
  _SENDSMSRESPONSE._serialized_end=98
  _RONSERVICE._serialized_start=100
  _RONSERVICE._serialized_end=182
# @@protoc_insertion_point(module_scope)
