# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import RonService_pb2 as RonService__pb2


class RonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSms = channel.unary_unary(
                '/RonService.RonService/SendSms',
                request_serializer=RonService__pb2.SendSmsRequest.SerializeToString,
                response_deserializer=RonService__pb2.SendSmsResponse.FromString,
                )


class RonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSms': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSms,
                    request_deserializer=RonService__pb2.SendSmsRequest.FromString,
                    response_serializer=RonService__pb2.SendSmsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RonService.RonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RonService.RonService/SendSms',
            RonService__pb2.SendSmsRequest.SerializeToString,
            RonService__pb2.SendSmsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
